### ISSUE TITLE
Segmentation fault on 32-bit arm when built with -mthumb

### ISSUE THREAD

**Issue by fornwall** [termux/proot#1]
@michalbednarski In https://github.com/termux/termux-packages/issues/761 it was noticed that proot segfaults when built with -mthumb on 32-bit arm  (which Termux&Android does by default to save binary size, as Thumb-2 seems to be recommended for most).

I worked around it by avoiding building proot with -mthumb in https://github.com/termux/termux-packages/commit/28c436bb8a9aab8f21dccada4bdc1f447a56b06c, so it's not really that important, and I guess 32-bit arm is slowly being deprecated as more and more new devices are 64-bit.

So not worth spending a lot of time on, but still interesting to see if you have an idea what could cause this :).

**Comment by michalbednarski** [comment]
It's caused by `r7` register conflict in loader (which is used as syscall number and when thumb mode is in use then also a frame pointer).

Problematic line is:
[`register word_t number asm("r7") = number_;`](https://github.com/termux/proot/blob/9fc1f2db56712f1bee38b568f5d4cf862763fd88/src/loader/assembly-arm.h#L73)

According to [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Local-Register-Variables.html) this is supposed to set register used for this variable in `asm` block (and that works, however `r7` (as frame pointer) value is clobbered).

I'd say that it's clang bug that this compiled but clobbered frame pointer (gcc fails compilation in this case)

Anyway, only loader does need to be compiled without `-mthumb`.
