### ISSUE TITLE
function not implemented in xiaomi, run success in other devices

### ISSUE THREAD

**Issue by sewerganger** [termux/proot#120]
I compile the binary for aarch64 and armv7, and create a right alpine env. proot tested successfully using nokia x6 and honor v10,  but all xiaomi devices fail to run redmi k20 (miui12 android10) , xiaomi 8 (miui12 android10) xiaomi 7 (miui 11 android 9)

```dart
  List<String> getArguments(List<String> cmds) {
    return [
      '-0',
      '--link2symlink',
      '-r',
      '$filesPath/rootfs',
      '-b',
      '/dev/',
      '-b',
      '/sys/',
      '-b',
      '/proc/',
      '-w',
      '/root',
      '/usr/bin/env',
      '-i',
      'HOME=/root',
      'PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin/',
      'LANG=C.UTF-8',
      ...cmds
    ];
  }
```

log
```
I/flutter ( 6319): proot info: Checking for f2fs case sensitivity bug
I/flutter ( 6319): proot info: f2fs bug not present on device
I/flutter ( 6319): proot info: binding = /proc
I/flutter ( 6319): proot info: binding = /sys
I/flutter ( 6319): proot info: binding = /dev
I/flutter ( 6319): proot info: binding = /data/data/com.sewerganger.lan_express/files/rootfs:/
I/flutter ( 6319): proot info: vpid 1: translate("/" + "/usr/bin/env")
I/flutter ( 6319): proot info: vpid 1:          -> "/data/data/com.sewerganger.lan_express/files/rootfs/bin/busybox"
I/flutter ( 6319): proot info: vpid 1: translate("/" + "/usr/bin/env")
I/flutter ( 6319): proot info: vpid 1:          -> "/data/data/com.sewerganger.lan_express/files/rootfs/usr/bin/env"
I/flutter ( 6319): proot info: exe = /usr/bin/env
I/flutter ( 6319): proot info: argv = /usr/bin/env -i HOME=/root PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin/ LANG=C.UTF-8 apk
I/flutter ( 6319): proot info: initial cwd = /root
I/flutter ( 6319): proot info: verbose level = 9
I/flutter ( 6319): proot info: pid 12151: access to "/proc/12151/fd" (fd 3) won't be translated until closed
I/flutter ( 6319): proot info: pid 12151: access to "/dev/ion" (fd 73) won't be translated until closed
I/flutter ( 6319): proot info: pid 12151: access to "/data/data/com.sewerganger.lan_express/
```

**Comment by michalbednarski** [comment]
This log is either cut or captured with too low verbosity, try capturing with `-v 9` or `PROOT_VERBOSE=9`

(also, does same problem occur withing Termux app?)

**Comment by sewerganger** [comment]
@michalbednarski hi i have added `PROOT_VERBOSE=9` to env that is all the log and termux runs well, i have tried android 10 devices but all failed, stderr: function not implemented, nokia x6(android 9) and honor v10(android 8) successed

code
```dart
  Future<ProcessResult> testProot(List<String> cmds,
      {Map<String, String> env}) async {
    bool seccomp = await Store.getBool(SANDBOX_NO_SECCOMP) ?? true;

    return Process.run(
      '$filesPath/proot',
      getTestArguments(cmds),
      workingDirectory: '/',
      environment: {
        'PROOT_NO_SECCOMP': seccomp ? '1' : '0',
        'PROOT_TMP_DIR': '$filesPath/tmp',
        'PROOT_VERBOSE': '9',
        ...?env
      },
      includeParentEnvironment: true,
    );
  }
```

```
  Future<ProcessResult> installNodeJs() async {
    return runProot(['apk', 'add', '--allow-untrusted', '/root/nodejs.apk']);
  }
```

the proot binay i compiled
[https://github.com/sewerganger/lan_express_desktop_bug_report](https://github.com/sewerganger/lan_express_desktop_bug_report)
the alpine env

![image](https://user-images.githubusercontent.com/45007226/92432609-410a3880-f1cd-11ea-91ac-cdd16ca3a152.png)

**Comment by michalbednarski** [comment]
> code
>
> ```dart
>         'PROOT_NO_SECCOMP': seccomp ? '1' : '0',
> ```

proot checks presence of `PROOT_NO_SECCOMP` variable, so `PROOT_NO_SECCOMP=0` is same as `PROOT_NO_SECCOMP=1` (and setting this variable can cause problems as it prevents detection of syscall order which might be needed for handling of blocked syscalls). Try removing this variable.

<details>
<summary>Additional notes on PROOT_NO_SECCOMP and PROOT_ASSUME_NEW_SECCOMP env variables</summary>

When you use `PROOT_NO_SECCOMP`, proot assumes old seccomp-SIGTRAP order as using that variable skips detection. Applying workarounds with new order requires adding `PROOT_ASSUME_NEW_SECCOMP`.

Proot informs about detected syscall order when running without `PROOT_NO_SECCOMP` and at least `-v 1`

<code>proot info: ptrace acceleration (seccomp mode 2, <b>new</b> syscall order) enabled</code>

"new" syscall order means running on kernel that includes following commit https://github.com/torvalds/linux/commit/a5cd110cb8369d6b37ef5ccfe56b3fa1338c9615
</details>

---

If removing that env variable didn't help this log still looks cut to me, try running that command through shell and using `>& file.txt` redirect instead of capturing results from app.

**Comment by sewerganger** [comment]
@michalbednarski  thank you very much,  i remove the `PROOT_NO_SECCOMP` ,  everything goes well
