### ISSUE TITLE
debootstrap won't work

### ISSUE THREAD

**Issue by ZhymabekRoman** [termux/proot#127]
Hello. I use proot-distro, Ubuntu 20. And debootstrap won't work :
![Screenshot_20201031-085923_Termux](https://user-images.githubusercontent.com/61125068/97769710-8b69bf00-1b57-11eb-98b8-5f294d9c5984.jpg)

```
$ debootstrap focal /home
mknod: /home/test-dev-null: Function not implemented
E: Cannot install into target '/home' mounted with noexec or nodev
```
What data do I need to provide so that you can solve the problem ?

**Comment by WMCB-Tech** [comment]
@ZhymabekRoman It seems Debootstrap won't work on non-rooted device (even prooted) because it mounts necessary filesystems. well Debootstrap in termux needs to be fix [here (further reading)](https://github.com/termux/termux-packages/issues/5932)

Try using linux deploy then use Debootstrap there (well I'm not sure it that works also).

**Comment by michalbednarski** [comment]
Debootstrap here tried to use `mknod` to create device nodes (which is not allowed for unprivileged processes nor usable within `/data`. There probably won't be emulation of that in proot, use Termux's patched debootstrap (available from Termux apt) instead of installing debootstrap inside proot-distro.

(If you want you might use debootstrap to create rootfs in home of `proot-distro` (`$PREFIX/var/lib/proot-distro/installed-rootfs/ubuntu/home`), although I'm not sure if that would be usable)

**Comment by ZhymabekRoman** [comment]
Ohhh, OK, thanks !
