### ISSUE TITLE
mprotect errors when running cool-retro-term

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot#161]
**Problem description**
When i try to run cool-retro-term in Arch Linux proot, it gives problems related to `mprotect()` system call error and some other Qt applications as well

![Screenshot_2021-06-04-12-06-06-27_8659c1e795b4b4239e38d87c88c077b3.jpg](https://user-images.githubusercontent.com/65075766/120744302-495d8d00-c52d-11eb-86e1-49f1d99bfd74.jpg)

**Steps to reproduce**
1. Install Arch Linux proot environment
2. Do `pacman -S cool-retro-term`
3. Run `cool-retro-term`

**Expected behavior**
It should run with a terminal-retro style

**Additional information**
This also happens in Ubuntu 20.04 as well when Installing `cool-retro-term`, but it seems this is some sort of Qt-related issue spitting out `mprotect` permission denied errors, not sure if this is Android specific, 

`termux-info` output:
```
Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf+ #2 SMP PREEMPT Thu Apr 15 23:25:42 CST 2021 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1933
```

Not sure if this is Android-specific or proot-specific bug, but any answers is appreciated! thanks

**Comment by WMCB-Tech** [comment]
This has something to do with Android, apparently `mprotect` and shared memory has issues with it, so apparently it is no-fix. closing this issue

**Comment by michalbednarski** [comment]
Sorry, I've had this issue analysed then forgot about it

Qt uses `memfd_create()` in order to create named memory allocation, however on Android such mapping cannot be made executable. When `memfd_create()` fails it'll fall back to using anonymous mapping.

Qt already handles this case when targeting Android (building QML application into .apk, but in this case we have Qt built for non-Android Linux)
https://code.woboq.org/qt5/qtdeclarative/src/3rdparty/masm/wtf/OSAllocatorPosix.cpp.html#48

Probably could be fixed by intercepting `memfd_create()` and failing it (if name matches one of those Qt uses for executable code)

**Comment by WMCB-Tech** [comment]
alright. i'mma reopening this issue

**Comment by michalbednarski** [comment]
So I've committed fix for mprotect failure, however at least on my device it looks like `cool-retro-term` still doesn't start shell, although it does render screen.

You can check fix so far by building proot from source

I'll yet have to still look at remaining issues

**Comment by WMCB-Tech** [comment]
Hi @michalbednarski I compiled proot from source then installed it somehow it still spits out same mprotect errors although i tested on Ubuntu 20.04 this time

am i missing something?

**Comment by WMCB-Tech** [comment]
actually that works on Debian sid (bullseye) but not Ubuntu 20.04

**Comment by layaachmad** [comment]
Is that fixed yet?

**Comment by WMCB-Tech** [comment]
Ubuntu 20.04 works with cool-retro-term

![Screenshot_2021-07-30-09-28-37-05_00dcaf2fcbe692c602a0957f19a66664.jpg](https://user-images.githubusercontent.com/65075766/127586147-dd95a307-a82a-41a4-b50a-c19d512c3f15.jpg)

instead of maybe denying `memfd_create` for specific call for qt (maybe for different versions of qt), probably i guess it can be denied in entirely 

```
diff --git a/src/syscall/enter.c b/src/syscall/enter.c
index f936d4d..8d79643 100644
--- a/src/syscall/enter.c
+++ b/src/syscall/enter.c
@@ -612,9 +612,7 @@ int translate_syscall_enter(Tracee *tracee)
 			}
 			/* If this memfd is one of those used by Qt/QML for executable code,
 			 * deny memfd_create() call and let Qt fall back to anonymous mmap.  */
-			if (0 == strcmp(memfd_name, "JITCode:QtQml")) {
-				status = -EACCES;
-			}
+			status = -EACCES;
 			break;
 		}
 	}
```

**Comment by michalbednarski** [comment]
With further testing of `cool-retro-term` I've found additional issues:

Since Qt writes `QSettings` `.ini` files through [`open(O_TMPFILE)`](https://code.woboq.org/qt5/qtbase/src/corelib/io/qtemporaryfile.cpp.html#_ZL17createUnnamedFileRiR18QTemporaryFileNamejP12QSystemError) + [`linkat("/proc/self/fd/...")`](https://code.woboq.org/qt5/qtbase/src/corelib/io/qtemporaryfile.cpp.html#_ZN20QTemporaryFileEngine22materializeUnnamedFileERK7QStringNS_19MaterializationModeE), after first when creating settings database through [`QtQuick.LocalStorage` (cool-retro-term side source)](https://github.com/Swordfish90/cool-retro-term/blob/1.1.1/app/qml/Storage.qml#L30) [(Qt side source)](https://code.woboq.org/qt5/qtdeclarative/src/imports/localstorage/plugin.cpp.html#_ZN18QQuickLocalStorage16openDatabaseSyncEP14QQmlV4Function), `.sqlite` file is created but no corresponding `.ini` file, so after first run following runs won't spawn shell.

I'm not sure about denying `open(O_TMPFILE)`, while that would be easiest fix I think that could break other apps.

Following could be worked around by manually creating needed `.ini` file after first run

```
echo -e '[General]\nDescription=StorageDatabase\nDriver=QSQLITE\nEstimatedSize=100000\nName=coolretroterm1\nVersion=1.0' > ~/.local/share/cool-retro-term/QML/OfflineStorage/Databases/27e743fe85b8912a46804fed99e8a9ab.ini
```

(Otherwise terminal will be nonfunctional, same happens on desktop when `.sqlite` file is present but `.ini` file is missing, alternatively remove `.sqlite` file)

(Hash in file name is `md5("coolretroterm1")`)

---

Second issue is that when running proot without seccomp acceleration (either due to `PROOT_NO_SECCOMP=1 PROOT_ASSUME_NEW_SECCOMP=1 proot` run or due to debugger being attached inside proot), PRoots [`handle_statx_syscall`](https://github.com/termux/proot/blob/master/src/tracee/statx.c) is called twice per tracee syscall, once from syscall exit handler and second time due to SIGSYS. When doing `statx(fd, "", AT_EMPTY_PATH, ...)`, first execution succeeds and set `x0` register to 0 to mark success, then next invocation will see `fd` argument in `x0` being set to zero add will stat wrong file (In this case `/dev/null`, providing `stx_size=0` and making `QSettings` skip reading file.

---

Third is that when touching terminal in [XServer XSDL](https://play.google.com/store/apps/details?id=x.org.server), `cool-retro-term` crashes with stack overflow, though haven't debugged this one yet as so far I've had tested with Qt built without XInput support.

**Comment by layaachmad** [comment]
XServer XSDL problem

**Comment by WMCB-Tech** [comment]
It seems everything is working now

![Screenshot_2021-08-16-13-26-39-10_86e29ab1b9fd3f2a477a649413bc8db4.jpg](https://user-images.githubusercontent.com/65075766/129523593-21ab4189-5179-4acc-be87-e474a0176615.jpg)

**Comment by michalbednarski** [comment]
Fixed version (mprotect and linkat issue) is now available in Termux apt repo
