### ISSUE TITLE
I cannot connect to my desktop using vncserver

### ISSUE THREAD

**Issue by zxllkada** [termux/proot#166]
After installing my desktop on nethunter using proot-distro.

I connected to my desktop before, after few minutes I got this output, now I cannot connect to my desktop.

What is that ?! 

```
./extension/sysvipc/sysvipc.c:90: int sysvipc_syscall_common(Tracee *, struct SysVIpcConfig *, _Bool): assertion "config->chain_state == CSTATE_SINGLE || config->chain_state == CSTATE_SHMAT_SOCKET" failed
proot warning: signal 6 received from process 538
```

**Comment by xeffyr** [comment]
Moved to proot repository since this isn't a problem of proot-distro script.

**Comment by michalbednarski** [comment]
This is crash in optional part of `proot`, you can disable it by adding `--no-sysvipc` after `proot-distro login`

In order to be able to fix underlying issue though, I'd need to be able to reporduce it, so at first you'd need to answer following questions:
* What kernel is your device running (`uname -a` result when ran outside `proot`)
* What desktop environment did you use (Xfce/Gnome/...)
* Is logging in sufficient to trigger crash?

**Comment by zxllkada** [comment]
> This is crash in optional part of `proot`, you can disable it by adding `--no-sysvipc` after `proot-distro login`
> 
> In order to be able to fix underlying issue though, I'd need to be able to reporduce it, so at first you'd need to answer following questions:
> 
> * What kernel is your device running (`uname -a` result when ran outside `proot`)
> * What desktop environment did you use (Xfce/Gnome/...)
> * Is logging in sufficient to trigger crash?


Thank you for your help.

The problem fixed when I use this  :

`proot-distro login nethunter - - no-sysvipc`

**Comment by T-Dynamos** [comment]
My uname -a
```
Linux localhost 3.18.31-perf-g040a88f #1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
```
My Shell
```
xfce
```
Still getting termux crash
