### ISSUE TITLE
[Bug]: Cannot create files due to "disk full"

### ISSUE THREAD

**Issue by Yisus7u7** [termux/proot#173]
### Problem description

![Screenshot_20210817-151118](https://user-images.githubusercontent.com/64093255/129831547-1bd4a9f3-af4f-4a47-8e1e-2e4535c207f5.png)

I installed kde plasma in termux

### What steps will reproduce the bug?

But the kde apps cannot create some files, a message appears saying that the disk is full

### What is the expected behavior?

And that's false, if I have space.

The problem happens in any facility and any phone

**Comment by michalbednarski** [comment]
Appears to be proot issue with `QSaveFile.commit()` (at least as far as I can see with quick testing with Kate (text editor), although issue there applies only to config files and not files saved by application)

Moved issue to proot repo and reopening

(though please be patient as I yet still have to debug particular root cause, there were recently fixes related to `QSaveFile` in proot although it appears that in previous version issue is also present so this isn't regression)

**Comment by Yisus7u7** [comment]
Dolphin also can't create files..

**Comment by Yonle** [comment]
Can confirm this issue in Android 8 with Alpine proot & Plasma installed.

**Comment by Yisus7u7** [comment]
> Can confirm this issue in Android 8 with Alpine proot & Plasma installed with following error:
> 
> ```
> kf.config.core: Couldn't write "/home/yonle/.config/plasma-localerc" . Disk full?
> ```

That error sucess in any distro, why will this happen..

**Comment by michalbednarski** [comment]
Should be fixed in newest proot update available in Termux apt repo

**Comment by Yonle** [comment]
It's fixed @michalbednarski. Good job 👍
