### ISSUE TITLE
Permission denied (src/ip_resolver.cpp:542)

### ISSUE THREAD

**Issue by HITers2018** [termux/proot#248]
I guess the latest proot or proot-distro may have some bugs. If I install python and jupyter notebook in termux directly , ipykernel can work well. But if I install python and jupyter notebook in alpine (with the latest proot-distro), it gets the err 'Permission denied (src/ip_resolver.cpp:542)' and the ipykernel cannot start. The bug also influence users who upgrade proot and proot-distro.
Here are the codes I use to install python and jupyter notebook.

> proot-distro install alpine
proot-distro login alpine
apk add python3
python3 -m ensurepip
pip3 install wheel
apk add gcc python3-dev
apk add build-base libjpeg-turbo-dev zlib-dev libxslt-dev jpeg-dev  openjpeg libxft libzmq qhull pixman cairo libgfortran openblas-dev brotli-dev freetype-dev libffi-dev
pip3 install notebook

if you run `jupyter notebook --allow-root ` and open a notebook, console displays the err 'Permission denied (src/ip_resolver.cpp:542)' and the ipykernel cannot start.
![Screenshot_2022-12-29-11-21-30-411_com termux](https://user-images.githubusercontent.com/45704621/209899120-8f42a2fd-f905-4460-a0c6-6807cc3d5fc9.jpg)

**Comment by HITers2018** [comment]
I just found that the bug only appears on my android 13 device (miui14), so the problem may be caused by android 13. It is strange that ipykernel runs well in termux directly but cannot run in termux-proot.  Is it possible to solve the problem?

**Comment by michalbednarski** [comment]
As a workaround you can `LD_PRELOAD` following library to make `libzmq` believe that `getifaddrs()` is unavailable as in WSL:

```c
#include <errno.h>
#include <ifaddrs.h>
int getifaddrs(struct ifaddrs **ifap) {
	errno = EOPNOTSUPP;
	return -1;
}
```

```sh
gcc skip_getifaddrs.c -o skip_getifaddrs.so -shared
LD_PRELOAD=/root/skip_getifaddrs.so jupyter notebook --allow-root
```

---

Proper solution would be probably to ask `libzmq` to not [`abort()` when `getifaddrs()` reports `EACCES` (due to SELinux denial)](https://github.com/zeromq/libzmq/blob/v4.3.4/src/ip_resolver.cpp#L537-L542). [Bionic, unlike glibc, knows about `RTM_GETLINK` being unavailable and is able to handle that case](https://cs.android.com/android/platform/superproject/+/master:bionic/libc/bionic/ifaddrs.cpp;l=309;drc=5a7f3ef9a8ac3f4548a4739df9910d0905691b98), but ultimately I'd say that the bug is `libzmq` crashing when `getifaddrs()` reports unexpected `errno`

---

Besides `RTM_GETLINK` unavailability, `getifaddrs()` in `glibc` (but not in `musl`) hiccups at attempting doing `bind()` on `AF_NETLINK` socket so `errno` there comes from `bind()`. In `musl`, errno comes from `sendto(..., {nlmsg_type=RTM_GETLINK})` (which would also happen in `glibc` if we'd skip `bind()`). In both cases `errno` is set to `EACCES`

Overriding `bind()` error however is in my opinion risks breaking other uses and implementing `sendto(..., {nlmsg_type=RTM_GETLINK})` would introduce significant amount of state into `proot`, so I'd like to avoid doing these on `proot` side

**Comment by feer9** [comment]
Hey, same issue here trying to run `Spyder IDE` inside of Termux. The workaround mentioned above works, but is there any chance this gets fixed upstream? Do `libzmq` maintainers know about this? Just asking to know if I should file an issue there.

**Comment by HITers2018** [comment]
i have not reported it to libzmq maintainers, so you can file the issuse there if you want the issuse to be fixed upatream.

**Comment by HITers2018** [comment]
i just use the workaround mentioned above, maybe it is better to get the help from the libzmq maintainers. the workaround is easy and useful, which is just a hook by using LD_PRELOAD. it does not change any  cpp source file.

**Comment by feer9** [comment]
Yeah, I ended up using the workaround too. I wanted to report the bug but didn't take the time to present it properly to the devs

**Comment by Cateners** [comment]
I asked Bing to help me write the code for using the getifaddrs function in Android within a proot container. This code does work for me.
https://github.com/Cateners/tiny_computer/tree/master/extra/getifaddrs_bridge

**Comment by ashengstd** [comment]
i encoutered the same probem in a flutter based code-server gui app, but it seems that no option is available in code-server to add the environment variable, is there any way to fix the problem, or how to make it work in vscode?

**Comment by ericli2333** [comment]
> i encoutered the same probem in a flutter based code-server gui app, but it seems that no option is available in code-server to add the environment variable, is there any way to fix the problem, or how to make it work in vscode?

Actually, I gave it up long  ago.But I remember that before I gave it up,  I used the proot environment to run the code-server or the jupyter. And that works. You can refer to my [blog](https://www.ericli.vip/2023/09/28/Blogs/termux%E9%85%8D%E7%BD%AE/) And follow my steps to make it work.My blog is written in Chinese, and you may try to use Google translator to understand it.

**Comment by josesho** [comment]
The workaround wasn't successful for me. Am on Android 14, running proot-distro Ubuntu. I believe I've linked the library properly; see below.

Any help would be appreciated! Else I will just use `virtualenv` in Termux itself instead of Conda... :(
![Screenshot_20240713_102402_Termux](https://github.com/user-attachments/assets/c86528fb-ddb5-45ec-ae38-912ec2621513)

**Comment by josesho** [comment]
OK, I realize you have to run the full command each time.

```shell
LD_PRELOAD=/root/skip_getifaddrs.so jupyter lab --allow-root
```

This works! Yay!!

**Comment by ericli2333** [comment]
congratulation, actually even i fail from time to time. this proot is not that stable.

**Comment by josesho** [comment]
For reference, this was the full list of steps I followed to successfully install Ubuntu in Termux via `proot-distro`, then get conda and Jupyter running inside the proot distro, and lastly having to manually create Jupyter kernels in the correct folder so Jupyter can see them.

https://www.notion.so/josesho/Installing-Analytics-Stack-in-Termux-4a6ff82d32974db4a4de27ee5e24ba45

**Comment by sofair** [comment]
I managed to patch libzmq by changing EINVAL(22) to EACCES(13), So zmq can return before the assertion failed.
perl -pi -e "/\x1F\x7C\x01\x71\x04\x18\x56\x7A\x60\x0E\x00\x54/\x1F\x7C\x01\x71\x04\x18\x56\x7A\x6E\x0E\x00\x54/g" /path/to/libzmq.so.5.2.5

**Comment by feer9** [comment]
> I managed to patch libzmq by changing EINVAL(22) to EACCES(13), So zmq can return before the assertion fail. Patch the aarch64 binary with perl -pi -e "/\x1F\x7C\x01\x71\x04\x18\x56\x7A\x60\x0E\x00\x54/\x1F\x7C\x01\x71\x04\x18\x56\x7A\x6E\x0E\x00\x54/g" /path/to/libzmq.so.5.2.5

Won't that work only for the specific build you have?

**Comment by pedropalb** [comment]
I tried to use @michalbednarski's workaround. But, after starting jupyter with `LD_PRELOAD=./skip_getifaddrs.so jupyter notebook`, when I create a new notebook with a given kernel, I get a `double free or corruption (out)` error:
```
[I 2024-12-26 08:32:52.562 ServerApp] Creating new notebook in /notebooks
[I 2024-12-26 08:32:52.657 ServerApp] Saving Untitled3.ipynb
[I 2024-12-26 08:32:53.561 ServerApp] Saving file at /notebooks/Untitled3.ib
[I 2024-12-26 08:32:53.591 ServerApp] Saving Untitled3.ipynb
double free or corruption (out)
zsh: abort      LD_PRELOAD=./skip_getifaddrs.so jupyter notebook
```

Did anyone face the same issue?

**Comment by mxl00474** [comment]
I had a same issue and found the solution. The problem is that Jupyter (ipykernel) try to use psutil to get the ip addresses in jupyter_client/localinterfaces.py. When I commented out the following code in _load_ips_psutil() and hardcode the IP address like below, it worked. (LD_PRELOAD is still necessary in this case as well.)

```
def _load_ips_psutil() -> None:
    """load ip addresses with netifaces"""
    import psutil

    global LOCALHOST
    local_ips = []
    public_ips = []

    # dict of iface_name: address_list, eg
    # {"lo": [snicaddr(family=<AddressFamily.AF_INET>, address="127.0.0.1",
    #   ...), snicaddr(family=<AddressFamily.AF_INET6>, ...)]}

    ###### Comment out here ######
    #for iface, ifaddresses in psutil.net_if_addrs().items():

    #    for address_data in ifaddresses:
    #        if address_data.family == socket.AF_INET:
    #            addr = address_data.address
    #            if not (iface.startswith("lo") or addr.startswith("127.")):
    #                public_ips.append(addr)
    #            elif not LOCALHOST:
    #                LOCALHOST = addr
    #            local_ips.append(addr)

    ###### Then add below ######
    public_ips.append("192.168.x.x")  # Your public IP address
    LOCALHOST="127.0.0.1"
    local_ips.append(LOCALHOST)
```

**Comment by George-Seven** [comment]
Got `getifaddrs()` working again. You can check out this -

https://www.reddit.com/r/termux/comments/1krao4i/makes_getifaddrs_work_again_in_prootdistro_fixing/

**Comment by George-Seven** [comment]
@josesho Miniconda has it's own python different from apt python. So after activate miniconda, you need to do this once (inside miniconda env) -

    . /.libnetstub/libnetstub.sh
