### ISSUE TITLE
ENOSYS: function not implemented, utime

### ISSUE THREAD

**Issue by jlmess77** [termux/proot#28]
The yarn, npm, nodejs, wget (just warning) and possible others can't run in the proot because of missing utime. The utimes was added but missing utime. Is it possible to add utime?
```
error https://registry.yarnpkg.com/@types/chai-string/-/chai-string-1.4.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOSYS: function not implemented, utime '/usr/local/share/.cache/yarn/v1/npm-@types/chai-string-1.4.1-3a9d22716c27f2759bf272a4dbbdb593f18399e3/LICENSE'"
```

**Comment by michalbednarski** [comment]
I've just added utime implementation (now on master branch), however I haven't yet fully tested it so please let me know if it works (so it can be pushed to apt repository; if doesn't then what architecture, kernel (`uname -a`) and Android version do you use)

**Comment by jlmess77** [comment]
Nice thanks! It doesn't work though. It's Pixelbook with Chrome OS and Termux (from Google Play). Here's info from chrome://system.

> Chrome OS: Version 68.0.3440.76 (Official Build) beta (64-bit)
> 
> Linux localhost 4.4.132-14159-g1212a1a7013c #1 SMP PREEMPT Mon Jul 23 22:30:35 PDT 2018 x86_64 Intel(R) Core(TM) i5-7Y57 CPU @ 1.20GHz GenuineIntel GNU/Linux
> 
> CHROMEOS_ARC_ANDROID_SDK_VERSION |   | 25
> CHROMEOS_ARC_VERSION |   | 4905628

Here's info in the Google Play perference:

> Android 7.1.1
> Android Security Level July 5,2018
> Build number R68-10718.63.0

I only know very basic of C. I have read in your patch of utime. You gave it "0". Isn't it supposed to make it to nanosecond to make same with utimensat()? Unless I misunderstand what it is supposed to be. I remembered I have seen libeio source code while ago that has utime() with 1e9.

https://github.com/kindy/libeio/blob/master/src/eio.c#L1935

What I am trying to do with the yarn is to build [Theia IDE](https://github.com/theia-ide/theia). It's kind of similar to VS code but can run without Electron.

**Comment by michalbednarski** [comment]
Ok, I've tried with Chrome OS emulator and it looks like the `utime` syscall just isn't compiled into kernel and calling it really returns `-ENOSYS`. The above `utime` implementation I've previously added was executed when syscall was blocked by seccomp and process got `SIGSYS` signal.

However in your case `utime` is not blocked by seccomp and process is not getting SIGSYS signal so above workaround is not executed. (Seccomp filters imposed by system were [introduced in Android 8.0](https://developer.android.com/about/versions/oreo/android-8.0-changes#security-all) and you can check that they are not set with `grep Seccomp /proc/self/status`). (Although it turns out that seccomp workarounds didn't work and proot couldn't start any program with system-imposed seccomp filters on X86/X86_64 - just fixed in commit above).

Anyway to use `utime` now you'll need to compile latest proot and apply filter blocking and raising `SIGSYS` on `utime` by using program below then launch proot in it. (Having `utime` that returns `-ENOSYS` and doesn't raise `SIGSYS` isn't currently supported by proot)

```c
/*
clang blockutime.c -o blockutime
./blockutime proot ./whatever_needs_utime_working
*/
#include <linux/seccomp.h>
#include <linux/filter.h>
#include <sys/prctl.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, char **argv)
{
	struct sock_filter statements[] = {
		/* Load the current syscall into the accumulator.  */
		BPF_STMT(BPF_LD + BPF_W + BPF_ABS, offsetof(struct seccomp_data, nr)),

		/* Compare the accumulator with the expected syscall:
		 * skip the next statement if not equal.  */
		BPF_JUMP(BPF_JMP + BPF_JEQ + BPF_K, 0x1e, 0, 1),

		/* Send SIGSYS.  */
		BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_TRAP),

		/* Otherwise allow */
		BPF_STMT(BPF_RET + BPF_K, SECCOMP_RET_ALLOW)
	};
	struct sock_fprog program = {
		.len = sizeof(statements) / sizeof(statements[0]),
		.filter = statements
	};

	int ret = prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0);
	if (ret != 0) { perror("prctl(PR_SET_NO_NEW_PRIVS)"); return 1; }
	ret = prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, &program);
	if (ret != 0) { perror("prctl(PR_SET_SECCOMP)"); return 1; }

	if (argc <= 1) { puts("No program to run specified"); return 1; }
	execvp(argv[1], argv + 1);
	perror("execvp");
}
```

And while we're at Chrome OS it looks like that Theia at least started (hasn't tried to open any file with it). It looks like Android runtime gets separate network interface than Chrome so you'll need to use `ifconfig` in Termux to get ip your server listens on (you won't be able to connect to it from Chrome at `127.0.0.1`).

And note on `utime` and zero nanoseconds: `utime` accepts structure with two longs (for modification and access time in seconds). Unlike libeio which uses [own timestamp format](https://github.com/kindy/libeio#user-content-TIME-REPRESENTATION), `utime` syscall allows only specifying time with second precision (providing fractions is not possible, if someone needs nanoseconds then they'll need to use different syscall). Although it doesn't really matter as we probably could just return zero without doing anything and that didn't cause any problem.

**Comment by michalbednarski** [comment]
`blockutime` is supposed to emulate enough of Android 8 to get yarn in proot running and above worked in Chrome OS emulator so I think running it on actual Chromebook shouldn't be much more trouble.

To see whats going on I'd ask for running another test:

```c
/* utime.c */
#include <sys/syscall.h>
#include <utime.h>
#include <stdio.h>
#include <unistd.h>
const char *f = "testfile";
struct utimbuf t = {
        .modtime = 400 * 24 * 3600,
        .actime = 800 * 24 * 3600
};

int main() {
        int ret;
#if 0
        ret = utime(f, &t); /* Calls futimesat(2) */
#else
        ret = syscall(__NR_utime, f, &t);
#endif
        puts(ret == 0 ? "OK\n" : "ERR\n");
        return 0;
}
```

```sh
$ clang utime.c -o utime
$ touch utestfile
$ ./blockutime proot ./utime
OK
```

Did this test print OK? If not, then whats output of
```sh
PROOT_VERBOSE=9 ./blockutime proot ./utime
```

**Comment by jlmess77** [comment]
It prints ERR. Here is output with the PROOT_VERBOSE=9.
[utime.txt](https://github.com/termux/proot/files/2259685/utime.txt)

**Comment by jlmess77** [comment]
Here's more info from the strace.

[utime-strace.txt](https://github.com/termux/proot/files/2259719/utime-strace.txt)

**Comment by jlmess77** [comment]
by the way, I did the "touch testfile" instead of "touch utestfile" because in your utime.c has "testfile".

**Comment by michalbednarski** [comment]
Version with fix is now available in apt repo. I've tested Theia to start and be at least able to open/save files on Chromebook emulator. I'm closing issue now but if you have further issues then feel free to ask.
