### ISSUE TITLE
Proot is giving errors in some devices , why ??

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#4]
proot --link2symlink tar xvf filename.tar.gz
It is giving error while extraction.... Why it is working properly in some devices and not in some devices..
Proot errors are different in different devices 👎
1.) proot error signal 7
2) signal 11
3) etc....

**Comment by michalbednarski** [comment]
> why ??

There are multiple possible reasons:
* Because kernel support for debugging interfaces (especially changing/cancelling syscall) varies across devices and some feature in your kernel is missing
* Because proot uses it's own ELF loader (in order to properly translate path to ELF linker) and executables on your device might conflict with it
* Because kernel interface uses same notification for both syscall entry and exit and proot is keeping own flag to track them and that flag got out of sync
* Probably few other reasons, the above are ones that we've already got workarounds for in this proot fork
* And possibly my fixes caused problem in other configuration, I'm just human too (and same goes to original proot authors)

> Proot errors are different in different devices :-1:
> 1.) proot error signal 7
> 2) signal 11

11 is `SIGSEGV`, an access to unmapped memory (or access violating memory protection setting)
7 is `SIGBUS`, loading instructions from unmapped memory (or memory whose protection settings disallows execution)
These two are similar, depending on CPU and/or kernel they might not be differentiated with and `SIGSEGV` being always reported.

Errors being different across devices could indicate different things being incompatible or just being different symptoms of same problem.

I'm fixing problems which I'm able to reproduce, signal 7 or 11 doesn't really tell me anything (and I'm pretty sure that for most devs `It crashed with SIGSEGV` isn't really much more information than just `It crashed`, see how proper proot bug report leading to fix looks at termux/termux-packages#1309)

Also, I'm maintaining this fork of proot (for Termux) in part of my personal free time, which I might not really have for this project in following month

> :-1:

I'm somewhat under impression that you're here to whine rather than having this fixed, in which case I'm unfortunately unable to help.

 (Also, I'm not sure why for user (as opposed to developer) having different errors on different devices worse than having same error across devices)

**Comment by sdrausty** [comment]
>David León Rodríguez
>
>Well, I think that I found the problem. The architecture of my proccesor is armv8 but the android version that samsung installed in my tablet is armv7. Your new commit ends in an error. (Check the red arrow)

[Check the red arrow]( https://plus.google.com/photos/photo/112476373588507941507/6485992159483264386?icm=true&iso=false) error. From https://plus.google.com/112476373588507941507/posts/15PgKMeHxE3

**Comment by Hax4us** [comment]
@sdrausty you r r8 in your situation..... But mine is 64 bit device and I m extracting Ubuntu 64 bit tar file from neo script and one strange thing is that I don't know how but frst time when I tried to install Ubuntu ......it worked but now...giving errors while installing like signal 7 or 11

**Comment by sdrausty** [comment]
>It's not an md5 issue anymore, [now I get this:](https://user-images.githubusercontent.com/14004943/32411980-afa3c332-c224-11e7-8ecb-a29ea21b804a.png) error from https://github.com/sdrausty/TermuxArch/issues/12

! [now I get this:](https://user-images.githubusercontent.com/14004943/32411980-afa3c332-c224-11e7-8ecb-a29ea21b804a.png)

**Comment by sdrausty** [comment]
@Hax4us both are 64bit errors, arm8l and x86_64. Something about the OS being 32bit on armv8l. See the post for details.

**Comment by Hax4us** [comment]
Sure I will try your TermuxArch but it will not work trust me...my proot is unstable.and see how your screenshot and my screenshot are different ....your proot is telling that "can't handle 64 bit programs " but see my screenshot
![intex aqua trend_2017-11-09-20-08-45](https://user-images.githubusercontent.com/30441647/32611723-5dff1d9a-c58c-11e7-8e02-3206431f5e69.png)

**Comment by sdrausty** [comment]
@Hax4us `vpid 1` seems to mean architecture mismatch afaikt. It's a fairly regular error when I am debugging the install script system detection routines for another device architecture.

**Comment by sdrausty** [comment]
@Hax4us try using `bsdtar`,  not `tar` too.

**Comment by Hax4us** [comment]
@sdrausty  thnx I will try bsdtar but..how.😅 bcz I want to install ubuntu proot so...how to change ubuntu.tar.gz into ubuntu.tar.gz using bsdtar ....and I have pc with Linux so can I try to extract Ubuntu.tar.gz file then again compress with bsdtar ....will it work ?

**Comment by sdrausty** [comment]
@Hax4us first `pkg install bsdtar`. Then edit the your script to use bsdtar instead of tar.

**Comment by Hax4us** [comment]
Closed

**Comment by sdrausty** [comment]
Are these issues related to Termux PRoot?  They only happen on some devices. 
1) https://github.com/sdrausty/TermuxArch/issues/28 Closed
1) https://github.com/sdrausty/TermuxArch/issues/33 Open
1) https://github.com/sdrausty/TermuxArch/issues/46 Closed

Thanks for the awesome work btw 🏄💦

**Comment by michalbednarski** [comment]
1 and 3 doesn't seem so, 2 maybe through i cannot say for sure.

Hang due to low entropy doesn't seem likely to me, you might try using usual `PROOT_NO_SECCOMP=1` and checking `PROOT_VERBOSE=9` logging

So far I've been mostly successful with issues I'm able to reproduce myself, anyway if you'd like to raise something here please open new issue.

**Comment by Kaliyan123** [comment]
![Screenshot_2022-11-18-07-14-58-51.jpg](https://user-images.githubusercontent.com/96758317/202598308-a200d3bb-443e-4604-9843-87fc94800f4b.jpg)


Please solve this problem 😬 it occurred when iam installing kali lynx
I need to solve this
