### ISSUE TITLE
cannot read file

### ISSUE THREAD

**Issue by myfreess** [termux/proot#45]
localhost:/home# ./micro
sh: ./micro: not found
localhost:/home# ls -l
total 12400
-rw-r--r--    1 root     root             0 Oct 20 13:42 list
-rwxr-xr-x    1 root     root      12694184 Oct 20 13:42 micro
localhost:/home#

I am using alpinelinux

**Comment by michalbednarski** [comment]
Not found (-ENOENT) when starting program might refer not only to lack of
executed file but also to interpreter (specified with #! in case of script,
for native executables (ELF) you can check interpreter (linker) using
`file` command).

If interpreter/linker is present and usable or you have problems with
checking that please run proot in verbose mode (`export PROOT_VERBOSE=9`
before starting proot/Alpine), use `script` command to capture terminal
output (`script` recording is saved by default to "typescript" file; finish
recording by exiting from shell) in order to provide it here)
