### ISSUE TITLE
Can't start TermuxArch, proot info: 1: terminated with signal 11

### ISSUE THREAD

**Issue by CecilRamza** [termux/proot#63]
I already installed TermuxArch succesfully, but when run: `startarch` it says:

`proot info: vpid 1: terminated with signal 11`

I tried every way to start TermuxArch, the output is the same.

Device: Xiaomi Redmi 6, MIUI ver. 10.3.2.0, Android ver. 8.1.0

**Comment by michalbednarski** [comment]
It's odd that install was successful (TermuxArch setup runs `tar` under `proot` in order to extract system, you have filesystem installed in `$HOME/arch`, right?), yet system failed to start.

You can try following:

1. Try with `PROOT_NO_SECCOMP=1` env var set
```
PROOT_NO_SECCOMP=1 startarch
```

2. Make sure you're not nesting proot (such as using `termux-chroot` and trying `startarch`)

3. Try using another shell:
```
unset LD_PRELOAD
proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data -b /dev/ -b /sdcard -b /data/data/com.termux/files/home -b /proc/ -b /storage/ -b /sys/ -w /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM=screen-256color /usr/bin/pacman -Syu dash
proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data -b /dev/ -b /sdcard -b /data/data/com.termux/files/home -b /proc/ -b /storage/ -b /sys/ -w /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM=screen-256color /usr/bin/dash
```

4. If still fails, set `PROOT_VERBOSE=9` and post log:
```
PROOT_VERBOSE=9 startarch &> log.txt
```
```

**Comment by CecilRamza** [comment]
The first way worked, now I can start TermuxArch.
Now I have issues with the configuration of TermuxArch, but they are independent of proot. Thank you very much.
