### ISSUE TITLE
proot warning: can't chdir

### ISSUE THREAD

**Issue by QkiZMR** [termux/proot#65]
Termux on Android Pie. I'm trying to proot `/data/data/com.termux/files/` like it was working earlier but no success.
```
u0_a164@localhost ~> proot -r /data/data/com.termux/files/ -q /usr/bin/fish
proot warning: can't chdir("/data/data/com.termux/files/home/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/bin/sh' not found (root = /data/data/com.termux/files, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
```
`/data/data/com.termux/files/` exists so warning is unreliable.

**Comment by xeffyr** [comment]
> /data/data/com.termux/files/ exists so warning is unreliable.

It doesn't exist inside proot.

**Comment by xeffyr** [comment]
And if you really need to execute `proot -r /data/data/com.termux/files/ -q /usr/bin/fish`, the correct command will be:
```
proot -b /data:/data -b /proc:/proc -b /system:/system -b /dev:/dev -r /data/data/com.termux/files/ /usr/bin/fish
```

Mountpoints `/data`, `/proc`, `/system` are required in order for to execute Termux programs. Also, the switch `-q` was misused - it is for qemu-user and should not be used standalone.

Mountpoint `/dev` is optional, but still required in order to use many programs.

**Comment by QkiZMR** [comment]
Thx, it works with all `-b` options. I dont know how it works earlier.
