### ISSUE TITLE
bug: nested chroot with qemu enabled

### ISSUE THREAD

**Issue by zaoqi** [termux/proot#67]
```
$ proot -0 -R . -q qemu-arm -b .:/chroot /bin/sh
# ls /chroot/host-rootfs/
## (Nothing)
# busybox chroot /chroot/ /bin/sh
# ls host-rootfs/
SWAP                desktopfs-pkgs.txt  lib                 mnt                 rootfs-pkgs.txt     sys
bin                 dev                 lib64               opt                 run                 tmp
boot                etc                 lost+found          proc                sbin                usr
crypto_keyfile.bin  home                media               root                srv                 var
## (expect Nothing,but )
# exit
```

**Comment by michalbednarski** [comment]
What host arch/kernel do you use?
Where is that qemu from?
Which rootfs do you use?

**Comment by zaoqi** [comment]
@michalbednarski 

```
$ uname -a
Linux zaoqi-pc 4.19.59-1-MANJARO #1 SMP PREEMPT Mon Jul 15 18:23:58 UTC 2019 x86_64 GNU/Linux
```
that qemu is from manjaro.
rootfs: https://alpinelinux.org/

**Comment by michalbednarski** [comment]
Looks like `/host-rootfs` is necessary to let qemu load it's libraries (such as `libc.so.6`) and also proot loader (`execve` implementation, opens executable and linker and maps them into memory) passes to `open(2)` paths that are from guest perspective which get translated by proot, so it must use `/host-rootfs/usr/bin/qemu-arm` and `/host-rootfs/lib64/ld-linux-x86-64.so.2`).

The execve part is under proot control and possibly in case of qemu we could skip proot loader altogether, however loading `libc` and other libraries happen inside qemu executable and only thing proot does is setting `LD_LIBRARY_PATH` so libraries are loaded from `/host-rootfs`

At that point, however I have a question what problem is `/host-rootfs` is causing. It should be noted that proot is mostly compatibility sandbox, not security one (it cannot guarantee security, mostly because paths passed to syscalls still live in tracee address spaces, removing `/host-rootfs` could only give false sense of security). Is `/host-rootfs` causing compatibility problem? Would renaming it solve it?

**Comment by ZhymabekRoman** [comment]
@zaoqi You do not have full-fledged command-line arguments to run the proot container, the campaign that you took from the official site of proot. And also, if I'm not mistaken, you need to run "qemu static arm".

**Comment by ZhymabekRoman** [comment]
If you want to run Alpine on your phone, I recommend using a specially made terminal based on Termux - https://github.com/xeffyr/alpine-term

**Comment by ZhymabekRoman** [comment]
@xeffyr, I think this topic can be closed.

**Comment by xeffyr** [comment]
Alright, there no answer to questions in https://github.com/termux/proot/issues/67#issuecomment-513446236 for long time, so I'm closing this.

Exposure of `/host-rootfs` is not really an issue.

> And also, if I'm not mistaken, you need to run "qemu static arm".

Supplying `-R` option is enough, if running Linux chroot on Linux distribution.

> If you want to run Alpine on your phone

That's was not a phone - https://github.com/termux/proot/issues/67#issuecomment-513083091.
