### ISSUE TITLE
proot warning: ptrace(PEEKDATA): I/O error

### ISSUE THREAD

**Issue by sxdqx** [termux/proot#70]
proot warning: ptrace(PEEKDATA): I/O error
proot warning: ptrace(PEEKDATA): I/O error
proot warning: ptrace(PEEKDATA): I/O error                        
proot warning: ptrace(PEEKDATA): I/O error
proot warning: ptrace(PEEKDATA): I/O error
proot warning: ptrace(PEEKDATA): I/O error
proot warning: ptrace(PEEKDATA): I/O error
gpg: can't connect to the agent: IPC connect call failed
gpg: Total number processed: 1                                    
gpg:               imported: 1

**Comment by michalbednarski** [comment]
What distro (and how it was installed) and commands you are running inside proot and whats you host system (`uname -a`)?

---

Not sure if related (as far as I see gpg (unlike ssh-agent) doesn't use `PR_SET_DUMPABLE`) but possibly related to #62 (Which has workaround described)

**Comment by sxdqx** [comment]
Ubuntu 18.04
Run "sudo apt-key add xx .key" Error that occurred

**Comment by kalmari246** [comment]
got same problem with arch linux, seems to be breaking sudo: ```bash
[kalmari@localhost ~]$ sudo
proot warning: ptrace(PEEKDATA): I/O error
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so: Bad address
sudo: fatal error, unable to load plugins
[kalmari@localhost ~]$
```

**Comment by ZZZXXX0110** [comment]
Same problem here, seems to be breaking sudo in Ubuntu.

Samsung Galaxy Note 9

**Comment by michalbednarski** [comment]
Filtering of `PR_SET_DUMPABLE` prctl has been added to proot, hopefully it fixes sudo (although sudo on my arm64 device didn't have problem, but I've seen versions of sudo which use above prctl and symptoms match, so hopefully this will fix it)

Please comment if still doesn't work after proot update (to 5.1.107-22 in Termux apt)

**Comment by 12702j** [comment]
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error
proot warning: ptrace(POKEDATA): I/O error  

Where is the problem

**Comment by RyanHARRIS18** [comment]
I hace the exact same error with a Samsung J727a my kali will boot but then when in it does not allow web browsing what is the solution?

**Comment by michalbednarski** [comment]
`ptrace(POKEDATA): I/O error` is generic error indicating that proot was unable write guest memory (either because address specified by guest process cannot be written to or some other problem).

There's ongoing issue related to similar error in #96 (which may or may not be same other commenters experience, however original issue with `sudo` (and `ssh-agent`) this thread was originally about was already resolved)

There's no solution in #96 yet, however it shows similar error message, so I'd suggest following situation there.

I'm closing this thread; If you have similar issue please first check if #96 (if it's still open) reproduction steps also trigger bug on your device and if so then wait for it to be resolved. If that also wasn't issue you've stumbled upon then please open new one. Please note that any comments that have no reproduction steps nor traces are unlikely to lead to solution.
